name: Build with zig 0.7.x

on:
  push:
  pull_request:
  schedule:
    - cron: '23 3 * * *'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.7.0
      - run: |
          wget --quiet https://github.com/metamath/set.mm/raw/develop/set.mm --output-document set.mm && zig build && time zig-cache/bin/zigmmverify
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.7.0
      - run: zig fmt --check build.zig src/*.zig
