name: Build with zig master

on:
  push:
  pull_request:
  schedule:
    - cron: '23 3 * * *'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: |
          curl --silent --location https://github.com/metamath/set.mm/raw/develop/set.mm --output set.mm
          zig build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check build.zig src/*.zig
